### ISSUE TITLE
AWX Extension

### ISSUE THREAD

**Issue by AbdouMechraoui** [spurin/diveintoansible-lab#107]
I would like to inquire if this lab could be extended to AWX use cases. I don't have access to home-lab, and I became aware of this lab through your Ansible course. It'd be really cool to have AWX image as a central node. I'm not sure if it's possible, but it would be very useful.

**Comment by spurin** [comment]
Hi @AbdouMechraoui 

I can't make any promises on this given the mechanisms for running AWX (as the move now is much more towards running in Kubernetes rather than standalone) but, I've added it to my follow-up list and we can leave this open as a feature request!

I'm wrapping up some other projects but will see if there's a way in which we can move this forward constructively as, having an AWX based controller would be awesome!

**Comment by spurin** [comment]
(just to note, accidentally clicked the invalid label when assigning this, I meant to click the help wanted.  Your thoughts and considerations are very valid and appreciated!)

**Comment by spurin** [comment]
AWX has gone down many different paths and is very much a Kubernetes based platform, closing for now.
