### ISSUE TITLE
Can't restart nging in Ansible Playbooks- Creating and Executing

### ISSUE THREAD

**Issue by ematie93** [spurin/diveintoansible-lab#22]
I'm trying execute nginx_playbook.yaml from ~/diveintoansible/Ansible Playbooks, Introduction/Ansible Playbooks, Creating and Executing/solution/04 whit no changes and I got this output:

TASK [Restart Nginx] *****************************************************************************************************************************************************************************************************************************
fatal: [ubuntu1]: FAILED! => {"changed": false, "msg": "Service is in unknown state", "status": {}}
fatal: [centos2]: FAILED! => {"changed": false, "msg": "Service is in unknown state", "status": {}}
fatal: [centos3]: FAILED! => {"changed": false, "msg": "Service is in unknown state", "status": {}}
fatal: [centos1]: FAILED! => {"changed": false, "msg": "Service is in unknown state", "status": {}}
fatal: [ubuntu2]: FAILED! => {"changed": false, "msg": "Service is in unknown state", "status": {}}
fatal: [ubuntu3]: FAILED! => {"changed": false, "msg": "Service is in unknown state", "status": {}}

I don't know what is wrong. I tried start the service manually and it's work whit no issue

**Comment by spurin** [comment]
Hi @ematie93 

This is an issue with the version of Ansible and systemctl, I've updated the images so that Ansible is on a newer version that has this bug resolved.

If you do the following, you should be good to go -

docker-compose stop
docker-compose rm
docker-compose pull
docker-compose up

Then, login as ansible and do -

rm -rf /home/ansible/.ssh/known_hosts
sudo rm -rf /root/.ssh/known_hosts

Then, re-run the playbook

**Comment by ematie93** [comment]
yay, this mi issue, thanks!!
