### ISSUE TITLE
 Cannot start service Ports are not available

### ISSUE THREAD

**Issue by GauravRaii** [spurin/diveintoansible-lab#31]
Hi James,

I am trying to get docker running on windows machine but receiving the following error:
Creating ubuntu2 ...
Creating centos3 ...
Creating ubuntu-c ...
Creating ubuntu1  ...
Creating ubuntu3  ...
Creating centos1  ...
Creating centos2  ...
Creating ubuntu1  ... error

ERROR: for ubuntu1  Cannot start service ubuntu1: Ports are not available: listen tcp 0.0.0.0:2222: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
Creating ubuntu-c ... error

ERROR: for ubuntu-c  Cannot start service ubuntu-c: Ports are not available: listen tcp 0.0.0.0:2221: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
Creating ubuntu2  ... error
....
![Desktop Screenshot 2021 05 23 - 23 29 19 54](https://user-images.githubusercontent.com/84680489/119271549-a731d100-bc1f-11eb-9e37-0b15d4ac9e63.png)
![Desktop Screenshot 2021 05 23 - 23 33 58 22](https://user-images.githubusercontent.com/84680489/119271552-ae58df00-bc1f-11eb-823e-53d7695dc9a7.png)

**Comment by spurin** [comment]
Hi @GauravRaii 

Could you do a quick process for me and reboot your system.  I've seen this one before just once and it resolved itself after the person restarted post Docker install.

Let me know how you get on and if this doesn't resolve it, we'll find the way to do it.

Thanks

**Comment by GauravRaii** [comment]
Thank you James, I continued to have this issue despite restarting docker.

I tried multiple things to fix the problem, from reinstalling the docker to resetting the pc. It seems to be working now.

But I will keep you informed if this happens again.

Thank you
Gaurav

**Comment by iamvijayp** [comment]
Hello James,

I'm also facing this issue, did some search and found the issue is with ports exclusion.
---
C:\Users\Vijay\diveintoansible-lab>netsh interface ipv4 show excludedportrange protocol=tcp

Protocol tcp Port Exclusion Ranges

Start Port    End Port
----------    --------
      5357        5357
      7200        7299
      7300        7399
      7400        7499
      7500        7599
      7600        7699
      7700        7799
      7800        7899
      7916        8015
      8016        8115
      8116        8215
     50000       50059     *

* - Administered port exclusions.
* ----
* 
I could see in .env you've added the ports.

# ttyd (web terminal) ports
UBUNTUC_PORT_TTYD=7681
UBUNTU1_PORT_TTYD=7682
UBUNTU2_PORT_TTYD=7683
UBUNTU3_PORT_TTYD=7684
CENTOS1_PORT_TTYD=7685
CENTOS2_PORT_TTYD=7686
CENTOS3_PORT_TTYD=7687
---

I tried changing this to 8301-8307 and was able to start the containers, but the web terminals won't work with that fix!
Any other solutions?

My windows Version	10.0.19043 Build 19043
