### ISSUE TITLE
Error while running docker-compose up

### ISSUE THREAD

**Issue by abhijanjoshi** [spurin/diveintoansible-lab#83]
I did all the steps that is mentioned in the readme.md file.
I see this error:
[cmd-log.txt](https://github.com/spurin/diveintoansible-lab/files/7670596/cmd-log.txt)
The .env file:
[env.txt](https://github.com/spurin/diveintoansible-lab/files/7670619/env.txt)

Please help me solve the issue

**Comment by spurin** [comment]
Hi @abhijanjoshi 

Thanks for reaching out to me on this.  I've looked through your setup and this looks fine.  How did you setup and download the diveintoansible-lab folder?  Was it via git, downloaded as a zip and extracted or some other way?

What happens if you run -

```
docker run --rm -v /host_mnt/c/users/inajph/diveintoansible-lab/config:/config ubuntu cat /config/guest_name
```

**Comment by abhijanjoshi** [comment]
Hi @spurin,

I downloaded it as zip file.
if I run the command you have given I see below:
![image](https://user-images.githubusercontent.com/72075510/145260442-12022899-09d3-407e-bbf1-de391dd550f5.png)

**Comment by spurin** [comment]
Hi @abhijanjoshi 

That suggests that Docker isn't running, could you please re-run Docker and let me know, thanks

**Comment by abhijanjoshi** [comment]
![image](https://user-images.githubusercontent.com/72075510/145447755-78572fa8-911f-4585-9098-cc60fa788427.png)

**Comment by spurin** [comment]
Okay, it looks as if your Docker instance doesn't have permissions to access local folders.

What happens if you run the following -

docker run --rm -v /host_mnt/c/users/inajph:/test ubuntu ls /test

docker run --rm -v /host_mnt/c/users:/test ubuntu ls /test

docker run --rm -v /host_mnt/c:/test ubuntu ls /test

docker run --rm -v /mnt/c:/test ubuntu ls /test

By the way, is there anything particular about this setup?  For example, is it a works system that might have a security profile?

**Comment by spurin** [comment]
Also, in Docker Settings, can you take a look under Resources, File Sharing.  A screenshot of this would be useful please
