### ISSUE TITLE
Installing the Ansible Lab

### ISSUE THREAD

**Issue by lozsui** [spurin/diveintoansible-lab#86]
I don't know how else I could sent you this feedback. On Ubuntu 20.04.3 I successfully could

> git clone https://github.com/spurin/diveintoansible-lab.git

> docker-compose up

Note that I had to make no editing of whatsoever. In particular no editing of .env. However I had to do that as user 'diveinto' which I find is not in line with your documentation where you are doing this as user 'james'.

**Comment by spurin** [comment]
Hi @lozsui 

Sorry to hear about this confusion.  With the new lab setup, it shouldn't matter at all what user you choose to use, any of them will work.

I'm currently going through the course and am refreshing all of the closed captions, rather than it having the autogenerated ones.  I have then on my list, the refresh of this video so will be picking this up very soon.

Hope this helps and appreciate you letting me know.
